version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-alpinegit-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpinegit
          tag-suffix: -giantswarm
          image: giantswarm/alpinegit
          dockerfile: ./alpinegit/default.dockerfile
          build-context: alpinegit
          filters:
            tags:
              only: "/^alpinegit.*/"
            branches:
              ignore: "main"
