version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-alpinegit-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpinegit
          tag-suffix: -giantswarm
          image: giantswarm/laszlo-alpinegit
          dockerfile: ./alpinegit/default.dockerfile
          build-context: alpinegit
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
#          filters:
#            tags:
#              only: /^v.*/
