version: 2.1
orbs:
  architect: giantswarm/architect@dev:98db3dcc1d48af2c456900073072703a3a324e75
workflows:
  build-alpine-envsubst:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-envsubst
          tag-suffix: -envsubst
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/envsubst.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
          #          filters:
          #            tags:
          #              only: /^v.*/
  build-alpine-yq:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-yq
          tag-suffix: -yq
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/yq.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
  #          filters:
  #            tags:
  #              only: /^v.*/
  build-alpine-giantswarm:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-giantswarm
          tag-suffix: -giantswarm
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/giantswarm.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
  #          filters:
  #            tags:
  #              only: /^v.*/
  build-alpine-giantswarm-sysctl:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-giantswarm-sysctl
          tag-suffix: -giantswarm-sysctl
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/sysctl.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
  #          filters:
  #            tags:
  #              only: /^v.*/
  build-alpine-python3:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-python3
          tag-suffix: -python3
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/python3.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
  #          filters:
  #            tags:
  #              only: /^v.*/

  build-alpine-kubectl:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-kubectl
          tag-suffix: -kubectl
          image: giantswarm/alpine
          dockerfile: ./alpine/kubectl.dockerfile
          build-context: alpine
