version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-alpine-envsubst:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-envsubst
          tag-suffix: -envsubst
          image: giantswarm/alpine
          dockerfile: ./alpine/envsubst.dockerfile
          build-context: alpine
          filters:
            tags:
              only: "/^alpine-envsubst.*/"
            branches:
              ignore: "main"
  build-alpine-yq:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-yq
          tag-suffix: -yq
          image: giantswarm/alpine
          dockerfile: ./alpine/yq.dockerfile
          build-context: alpine
          filters:
            tags:
              only: "/^alpine-yq.*/"
            branches:
              ignore: "main"
  build-alpine-giantswarm:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-giantswarm
          tag-suffix: -giantswarm
          image: giantswarm/alpine
          dockerfile: ./alpine/giantswarm.dockerfile
          build-context: alpine
          filters:
            tags:
              only: "/^alpine-giantswarm.*/"
            branches:
              ignore: "main"
  build-alpine-giantswarm-sysctl:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-giantswarm
          tag-suffix: -giantswarm-sysctl
          image: giantswarm/alpine
          dockerfile: ./alpine/sysctl.dockerfile
          build-context: alpine
          filters:
            tags:
              only: "/^alpine-giantswarm.*/"
            branches:
              ignore: "main"
  build-alpine-python3:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-python3
          tag-suffix: -python3
          image: giantswarm/alpine
          dockerfile: ./alpine/python3.dockerfile
          build-context: alpine
          filters:
            tags:
              only: "/^alpine-python3.*/"
            branches:
              ignore: "main"
  build-alpine-bats:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: alpine-bats
          tag-suffix: -bats
          image: giantswarm/alpine
          dockerfile: ./alpine/bats.dockerfile
          build-context: alpine
          filters:
            tags:
              only: "/^alpine-bats.*/"
            branches:
              ignore: "main"
