version: 2.1
orbs:
  architect: giantswarm/architect@dev:2a9e477cc3e2fad44e79547b0ca8ce142e2f6fc4

workflows:
  build-alpine-envsubst:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          tag-prefix: alpine-envsubst
          tag-suffix: envsubst
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/envsubst.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
#          filters:
#            tags:
#              only: /^v.*/
  build-alpine-yq:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          tag-prefix: alpine-yq
          tag-suffix: yq
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/yq.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
  #          filters:
  #            tags:
  #              only: /^v.*/
  build-alpine-giantswarm:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          tag-prefix: alpine-giantswarm
          tag-suffix: giantswarm
          image: giantswarm/laszlo-alpine
          dockerfile: ./alpine/giantswarm.dockerfile
          build-context: alpine
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
  #          filters:
  #            tags:
  #              only: /^v.*/
