version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-calicoctl-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: calicoctl
          image: giantswarm/calicoctl
          dockerfile: ./calicoctl/default.dockerfile
          build-context: calicoctl
          filters:
            tags:
              only: "/^calicoctl.*/"
            branches:
              ignore: "main"
