version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-calicoctl-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: calicoctl
          image: giantswarm/laszlo-calicoctl
          dockerfile: ./calicoctl/default.dockerfile
          build-context: calicoctl
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
          filters:
            tags:
              only: "^calicoctl.*"
            branches:
              ignore: "main"
