version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-fluent-bit-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: fluent-bit
          tag-suffix: -aws-plugins
          image: giantswarm/laszlo-fluent-bit
          dockerfile: ./fluent-bit/default.dockerfile
          build-context: fluent-bit
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
          filters:
            tags:
              only: "^fluent-bit/v.*"
            branches:
              ignore: "main"
