version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-fluent-bit-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: fluent-bit
          tag-suffix: -aws-plugins
          image: giantswarm/fluent-bit
          dockerfile: ./fluent-bit/default.dockerfile
          build-context: fluent-bit
          filters:
            tags:
              only: "/^fluent-bit.*/"
            branches:
              ignore: "main"
