version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-kube-apiserver-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: kube-apiserver
          tag-suffix: -giantswarm
          image: giantswarm/laszlo-kube-apiserver
          dockerfile: ./kube-apiserver/default.dockerfile
          build-context: kube-apiserver
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
          filters:
            tags:
              only: "/^kube-apiserver.*/"
            branches:
              ignore: "main"
