version: 2.1
orbs:
  architect: giantswarm/architect@5.2.1

workflows:
  build-module-b:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          image: giantswarm/laszlo-monorepo-module-b
          dockerfile: ./module-a/Dockerfile
          build-context: module-b
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
#          filters:
#            tags:
#              only: /^v.*/
