version: 2.1
orbs:
  architect: giantswarm/architect@5.2.1

workflows:
  build-module-b:
    jobs:
#      - run:
#          name: Setup environment variables
#          command: |-
#            echo 'export ARCHITECT_MONOREPO="true"' >> "$BASH_ENV"
#            echo 'export ARCHITECT_MONOREPO_MODULE_NAME="module-b"' >> "$BASH_ENV"
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          image: giantswarm/laszlo-monorepo-module-b
          dockerfile: ./module-a/Dockerfile
          build-context: module-b
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
        environment:
          ARCHITECT_MONOREPO: "true"
          ARCHITECT_MONOREPO_MODULE_NAME: "module-b"
#          filters:
#            tags:
#              only: /^v.*/
