version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-mysql-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: mysql
          tag-suffix: -giantswarm
          image: giantswarm/laszlo-mysql
          dockerfile: ./mysql/default.dockerfile
          build-context: mysql
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
          filters:
            tags:
              only: "^mysql\/v.*"
            branches:
              ignore: "main"
