version: 2.1
orbs:
  architect: giantswarm/architect@dev:98db3dcc1d48af2c456900073072703a3a324e75

workflows:
  build-sonobuoy:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: sonobuoy
          tag-suffix: -alpine-giantswarm
          image: giantswarm/laszlo-sonobuoy
          dockerfile: ./sonobuoy/default.dockerfile
          build-context: sonobuoy
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
#          filters:
#            tags:
#              only: /^v.*/
