version: 2.1
orbs:
  architect: giantswarm/architect@5.8.0

workflows:
  build-sonobuoy-default:
    jobs:
      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          git-tag-prefix: sonobuoy
          tag-suffix: -alpine-giantswarm
          image: giantswarm/laszlo-sonobuoy
          dockerfile: ./sonobuoy/default.dockerfile
          build-context: sonobuoy
          registries-data: |-
            private gsociprivate.azurecr.io ACR_GSOCIPRIVATE_USERNAME ACR_GSOCIPRIVATE_PASSWORD true
          filters:
            tags:
              only: "^sonobuoy.*"
            branches:
              ignore: "main"
